project:
  type: website
  output-dir: docs

website:
  title: "Menu"
  favicon: "ensai.png"
  sidebar: 
    background: "#95D5B2"
    style: "docked"
    search: true
    contents: 
      - section: "Ensai 3A"
        contents: 
          - href: posts/ValueAtRisk/ValueAtRisk.ipynb
            text: "Value at Risk"
          - href : posts/MasteringFinancialData/index.qmd
            text: "Mastering Financial Data"
          - href : posts/obligation/index.ipynb
            text: "Courbe de taux"
      - section: climat
        contents: 
          - href: posts/ClimateScenario/index.qmd
            text: "Scénarios climatiques"
          - href: posts/ClimatMeteo/index.qmd
            text: "Différence entre climat et météo"
          - href: posts/NotionCle/index.qmd
            text: "Notions clés pour comprendre le changement climatique"
          
    
          
  navbar:
    background: "#40916C"
    search: true
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/junior-jumbong-258330211/
      - icon: github
        text: Github
        href: https://github.com/Jumbong
format:
  html:
    theme: cosmo
    css: styles.css

editor: 
  language: python
  style: darcula
  theme: light
execute:
  freeze: auto


