project:
  type: website
  output-dir: docs

website:
  title: "Menu"
  favicon: "ensai.png"
  sidebar: 
    background: "#40916C"
    style: floating
    search: true
    contents: 
      - section: "Ensai 3A"
        contents: 
          - index.qmd
          - posts/ValueAtRisk/ValueAtRisk.ipynb
          - posts/MasteringFinancialData/index.qmd
          
          
    
          
  navbar:
    background: "#95D5B2"
    search: true
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/junior-jumbong-258330211/
      - icon: github
        text: Github
        href: https://github.com/Jumbong
format:
  html:
    theme: cosmo
    css: styles.css


execute:
  freeze: auto


