---
title: "Market risk generalities"
author: "Jumbong Junior"
date: "2023-11-04"
categories: [news]
format:
  html:
    toc: true
    toc-title: "Sommaire"
    html-math-method: katex

---

# What is market risk ?

A market risk is a risk of loss an investment value due to a variation of the market factors. The market factors are the parameters that influence the price of a financial instrument. The most common market factors are:

- Interest rates
- Equity prices
- Foreign exchange rates
- Commodity prices

The interest rate risk is the risk that the value of a financial instrument(ex:bond) will decline due to an increase of the interest rates.

C'est donc une offre dont la valeur va baisser si les taux augmentent. C'est le cas des obligations.

Exemple : A zero coupon bond with a face value of 1000€ and a maturity of 10 years. The interest rate is 5%. The value of the bond is $$p = \frac{1000}{(1+0.05)^{10}} = 613.$$


If the interest rate increases to 6%, the value of the bond is $$p = \frac{1000}{(1+0.06)^{10}} = 558$$

Une autre chose qu'il faut remarquer est que si les taux d'intérêts augmentent, la valeur des obligations diminue. Qu'elle est l'interprétation économique de cela ?

## Augmentation des taux d'intérêts entraine une diminution de la valeur des obligations

Si les taux d'intérêts augmentent, les investisseurs peuvent obtenir plus de rendements sur les nouvelles obligations, la demande pour les anciennes obligations diminue et donc leur prix diminue.

## Curve risk

Une banque se finance sur le coup terme et prête sur long terme. Si les taux d'intérêts augmentent, la banque va devoir payer plus cher pour se financer et donc son bénéfice va diminuer.

Comment le régulateur peut diminuer l'inflation  ?
En augmentant les taux d'intérêts, cela rend le credit plus cher, ce qui peut réduire les dépenses des ménages et des entreprises et les investissements. Ceci réduit la demande de crédit et dont l'offre de monnaie. Cela réduit l'inflation.

Donc pour relancer l'économie, on peut baisser les taux d'intérêts.

Finalement, pour que la banque puisse se financer à coup terme et prêter à long terme, il faut une absence d'une corrélation entre les taux d'intérêts à court terme et à long terme.



Equity price risk(le risque du prix des actions, ETF (Exchange-Traded Funds) : ) is the risk associated with the volatility of the stock prices. It can be divided into two categories: general market risk and specific risk.

Let $R_i$ the return of a portfolio of N equities.
The global return $R_p = \frac{\sum_{i=1}^{N}R_i}{N}$. If we denode by $R_m$ the return of the market, the global return can be written as $R_i = \beta R_m + \alpha_i$ where $\beta$ is the sensitivity of the portfolio to the market and $\alpha$ is the specific return of the portfolio.

Foreign exchange risk is the risk that the value of a financial instrument will decline due to a change in the exchange rate.

The price of commodities is influenced by the supply and demand.

The market risk can be measured by several methods: sensitivity analysis, scenario analysis, value at risk, stress testing.

# Measuring market risk

## Sensitivity-based methods

### Duration

La duration exprime comment un porte-feuille est sensible aux variations des taux d'intérêts. 

Exemple: Un porte-feuille avec une duration de 5 ans signifie que si les taux d'intérêts augmentent de 1%, la valeur du porte-feuille va diminuer de 5%.

Donc une duration élevée signifie un risque élevé.

Maintenant si on a deux obligations(bonds):
Le premier de nominal 1000, maturité 10 ans, de prix 900 et de coupon 5%.
Le deuxième de nominal 1000, maturité 10 ans, de prix 1100 et de coupon 7%.

Sur quels bond va t-on investir ?

Pour répondre à cette question, nous avons besoin d'un outil: the yield to maturity.

The yield to maturity est le taux d'intérêt qui rend la valeur actuelle des flux de trésorerie futurs égale au prix actuel du titre.
Mathématiquement,
$$P = \sum_{i=1}^{N} \frac{C_i}{(1+y)^i}$$

où $C_i = nominal* coupon$ $i!=N$
$C_N = nominal + coupon*nominal$

Il faut deux hypothèses pour calculer le yield to maturity:
- Le coupon est réinvesti au taux d'intérêt du marché.
- Le titre est détenu jusqu'à la maturité.
On a défini le yield to maturity, on peut définir la duration. 

La duration est la sensibilité de la valeur d'un titre par rapport au yield to maturity. Mathématiquement,

$$D = -\frac{1}{P}\frac{dP}{dy}$$.

**Conséquence de la duration**:

- Si le taux d'intérêt augmente diminue, nous allons investir dans un porte-feuille avec une duration élevée.

- Soit une obligation dont le prix est de 90 qui paye des coupons annnuels de 5% de nominal 1000 et de maturité 5 ans.

Determinons son yield to maturity.

On sait que le yield to maturity est le taux d'intérêt qui rend la valeur actuelle des flux de trésorerie futurs égale au prix actuel du titre.

Mathématiquement,
$$P = \sum_{i=1}^{N} \frac{C_i}{(1+y)^i}$$

Pour déterminer la duration, on a besoin de calculer la dérivée de P par rapport à y.

on sait que la dérivée peut être calculée comme une limite de la formule suivante:

$$\frac{dP}{dy} = \lim_{\Delta y \to 0} \frac{P(y+\Delta y) - P(y- \Delta y)}{2 \Delta y}$$

Ainsi si on a déterminé le yield to maturity, on peut déterminer la duration.
Il faut pour cela, calculer le prix de l'obligation pour deux valeurs de y: $y+\Delta$ et $y-\Delta y$.
Prenons $\Delta$ = 0.01
Pour y1 = $y+\Delta$
$$P(y+\Delta) = \sum_{i=1}^{N} \frac{C_i}{(1+y+\Delta)^i}$$

pour y2 = $y-\Delta$
$$P(y-\Delta) = \sum_{i=1}^{N} \frac{C_i}{(1+y-\Delta)^i}$$

Finalement,
$D = -\frac{1}{P}\frac{P(y+\Delta) - P(y- \Delta y)}{2 \Delta y}$

Il y'a une hypothèse forte derrière la duration: Une courbe de déplacement parallèle. C'est à dire que si les taux d'intérêts augmentent de 1%, la courbe des taux d'intérêts va se déplacer parallèlement vers le haut.

## The Greeks

La valeur d'un porte-feuille dépend de plusieurs facteurs, qui peuvent interagir entre eux. Pour mesurer l'impact de ces facteurs sur la valeur du porte-feuille, on utilise les lettres grecques : delta, gamma, vega, theta, rho.

### Delta

Le delta exprime le changement entre un changement de la valeur du porte-feuille et un changement de la valeur du sous-jacent. Exemple : Soit $C_0$ le prix d'une option de maturité T et de strike k. Soit $S_t$ le prix du sous-jacent à la date t.

payoff de l'option : $max(S_T - k, 0)$,
le prix de l'option est le payoff actualisé :
$$C_0 = \frac{max(S_T - k, 0)}{(1+r)^T}$$

Les facteurs de risques de cette option sont : le prix du sous-jacent, le taux d'intérêt et la volatilité.

Le delta de cette option est : $\frac{\partial C_0}{\partial S_t}$

Comment se couvrir de la variation du prix du sous-jacent ?

Il faut construire un porte-feuille qui a un delta égal à 0. C'est à dire que si le prix du sous-jacent augmente, la valeur du porte-feuille ne change pas.

on peut par exemple considéré un porte-feuille de prix $P^{'} = C_0 + \alpha S_t$.
La nouvelle option est de sensibilité nulle par rapport au prix du sous-jacent si $\alpha = -\frac{\partial C_0}{\partial S_t}$.
Ceci revient à dire que pour se couvrir du risque de la variation de prix du sous-jacent, il faut vendre à decouvert c'est-à-dire short selling $\frac{\partial C_0}{\partial S_t}$ unités du sous-jacent. 
Le delta d'une action est 1.

Un portefeuille avec un delta de 0 est option risque neutre. Il est construit pour (hedging purposes) se couvrir du risque de la variation du prix du sous-jacent.

### Gamma

Le gamma est la dérivée seconde du prix de l'option par rapport au prix du sous-jacent. Il mesure la sensibilité du delta par rapport au prix du sous-jacent.
Son implication dans le cas d'un portefeuille delta-neutre est qu'il a besoin d'être réajusté régulièrement si son gamma est élevé.
Le gamma est donc de mesurer le degré d'exposition au risque qu'une position couverte(hedged position) dévellopera si la couverture(hedge) n'est pas réajustée.

### Vega

Le vega mesure le changement du prix de l'option par rapport à la volatilité du sous-jacent. Il mesure la sensibilité du prix de l'option par rapport à la volatilité du sous-jacent.

Un portefeuille avec un vega de 0 est vega-neutre. Il est construit pour se couvrir du risque de la variation de la volatilité du sous-jacent. C'est-à-dire qu'il est insensitive à la variation de la volatilité du sous-jacent.

### Theta and Rho

Le Theta et le rho déterminent respectivement le taux de changement de la valeur d'un portefeuille par rapport au temps to maturity et par rapport au taux d'intérêt.

En practique, les sensibilités d'un portefeuille sont calculées intensivement, intra-day(à l'intérieur de la journée) et quotidiennement pour chaque traded product. Ils sont utilisées par les traders afin de gérer leur risque, their position(hedging) et par les managers pour expliquer leur perte et leur profit(P&L).
Cependant, elles souffrent de plusieurs limitations: elles ne peuvent pas être comparées entre plusieurs activités pour conclure qu'une activité est plus risquée qu'une autre.




